name: stat-comps

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.12

  - ipykernel
  - ipython
  - black

  - polars
  - pandas
  - pyarrow

  - numpy
  - pytorch
  - captum

  # - pytorch-cuda=11.8

  - tqdm
  - requests

